#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: RICH-20
    password: $6$NztZo2AD5X08yOiw$glHxK8dOmYr1xbgKv5wAaNpepy6vRzUihjvZEAzBboYOJqomy7UpyjXH3VLzI0TVAkFuJaXxR/AO>
    realname: Marshal Miller
    username: marshalmiller
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      eno1:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-desktop-minimal
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    config:
    - transport: pcie
      preserve: true
      id: nvme-controller-nvme0
      type: nvme_controller
    - ptable: gpt
      serial: BC511_NVMe_SK_hynix_256GB_ND11N866611001U1C_1
      wwn: nvme.1c5c-4e4431314e383636363131303031553143-4243353131204e564d6520534b2068796e6978203235364742-000>
      nvme_controller: nvme-controller-nvme0
      path: /dev/nvme0n1
      wipe: superblock
      preserve: false
      name: ''
      grub_device: false
      id: disk-nvme0n1
      type: disk
    - device: disk-nvme0n1
      size: 1127219200
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
      offset: 1048576
      path: /dev/nvme0n1p1
      id: partition-4
      type: partition
    - fstype: fat32
      volume: partition-4
      preserve: false
      id: format-5
      type: format
    - device: disk-nvme0n1
      size: 32000442368
      wipe: superblock
      flag: swap
      number: 2
      preserve: false
      offset: 1128267776
      path: /dev/nvme0n1p2
      id: partition-5
      type: partition
    - fstype: swap
      volume: partition-5
      preserve: false
      id: format-6
      type: format
    - path: ''
      device: format-6
      id: mount-6
      type: mount
    - device: disk-nvme0n1
      size: 150000893952
      wipe: superblock
      number: 3
      preserve: false
      offset: 33128710144
      path: /dev/nvme0n1p3
      id: partition-6
      type: partition
    - fstype: btrfs
      volume: partition-6
      preserve: false
      id: format-7
      type: format
    - path: /
      device: format-7
      id: mount-7
      type: mount
    - device: disk-nvme0n1
      size: 72929509376
      wipe: superblock
      number: 4
      preserve: false
      offset: 183129604096
      path: /dev/nvme0n1p4
      id: partition-7
      type: partition
    - fstype: btrfs
      volume: partition-7
      preserve: false
      id: format-8
      type: format
    - path: /home
      device: format-8
      id: mount-8
      type: mount
    - path: /boot/efi
      device: format-5
      id: mount-5
      type: mount
    swap:
      size: 0
timezone: America/New_York
updates: security
version: 1
